### ISSUE TITLE
[BUG] Turret Crashes Local Server

### ISSUE THREAD

**Issue by KaleThyself** [HALOMAXX/BLREdit#18] opened 2022-10-28 19:11 UTC
When using a turret from the depot in a local server against bots, the server immediately disconnects the player and crashes. 

### BLREdit Version:
v.0.7.3

### Logs:
[BLRevive-1666983601.log](https://github.com/HALOMAXX/BLREdit/files/9891139/BLRevive-1666983601.log)

**Comment by HALOMAXX** [comment] 2022-10-30 17:25
not sure if it's because of BLREdit but changed the botmatch start behaviour (now also starts the client) to minimise this error.

**Comment by HALOMAXX** [comment] 2023-05-01 02:01
can't reproduce this problem on my end and haven't gotten more complaints about this problem will close this for now.

**Closed by HALOMAXX** 2023-05-01 02:01 UTC
